package com.example.androidbasic.data.local

import androidx.room.Entity
import androidx.room.PrimaryKey

/**
 * Created by Tirth Patel.
 */

@Entity(tableName = "quote")   //This class our database entity
data class Quote(
    @PrimaryKey(autoGenerate = true)
    val id: Int,
    val text: String,
    val author: String,
)

/*
    When autoGenerate is set to true, it means that the primary key value for the entity will be
    automatically generated by the database system. Typically, this is used with integer or long
    primary key types, and the database will automatically assign a unique value to the primary
    key when a new record is inserted.

    In this example, the id property is the primary key, and autoGenerate = true indicates that
    Room should automatically generate unique values for the id when inserting new Quote objects
    into the database.
*/

/*
MVVM SETUP
  1. Room DataBase Setup
       - Entity
       - DAO
       - Database

   2.Repository

   3.ViewModel & ViewModelFactory
*/
